a = int(input('Enter Number :'))
b = int(input('Enter Number :'))
c = int(input('Enter Number :'))
d = int(input('Enter Number :'))
e = int(input('Enter Number :'))
f = int(input('Enter Number :'))
g = int(input('Enter Number :'))
h = int(input('Enter Number :'))
s = set()
s.add(a)
s.add(b)
s.add(c)
s.add(d)
s.add(e)
s.add(f)
s.add(g)
s.add(h)
print(s)

