import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

sample_text = '''In the heart of the sprawling, ancient forest, where sunlight dappled through the thick canopy like liquid gold and the air hummed with the unseen life of countless creatures, stood an oak tree of remarkable age and size. Its gnarled branches, thick as a man's torso, reached skyward, a silent testament to centuries of growth, weathering storms, and basking in the benevolent gaze of the sun. The bark, a tapestry of deep furrows and ridges, harbored miniature ecosystems of mosses, lichens, and tiny insects, each playing its part in the intricate web of the forest. At its base, a small, clear stream babbled over smooth, moss-covered stones, its gentle murmur a constant lullaby to the surrounding flora and fauna.

Birds of vibrant plumage flitted between the leaves, their songs a joyful symphony that echoed through the verdant halls. Squirrels, with their bushy tails held high, darted up and down the trunk, burying and unearthing nuts with an energy that seemed boundless. In the undergrowth, ferns unfurled their delicate fronds, reaching towards the filtered light, while wildflowers of every hue dotted the forest floor, their petals a splash of vibrant color against the earthy tones. The scent of damp earth, decaying leaves, and the sweet perfume of blossoms hung heavy in the air, a rich, organic fragrance that spoke of life and renewal.

As dusk began to settle, painting the sky in hues of orange, pink, and purple, the forest took on a different character. The daytime sounds gradually subsided, replaced by the rustling of nocturnal creatures beginning their rounds. Owls called to each other from hidden perches, their haunting hoots drifting through the trees. Fireflies began to flicker like tiny, ephemeral stars, their gentle glow illuminating the deepening shadows. The stream's babble seemed to grow louder in the quiet, its constant flow a reminder of the unstoppable passage of time. The ancient oak stood silhouetted against the twilight sky, a silent sentinel watching over the sleeping forest, its roots reaching deep into the earth, grounding it against the winds of change, a timeless symbol of strength and endurance in a world that is constantly in motion. This scene, repeated through countless days and nights, years and decades, forms a small but vital part of the grand, unfolding narrative of the natural world, a story written in sunlight and shadow, growth and decay, life and death, a story that continues, ever evolving, ever enduring.'''
tokens = word_tokenize(sample_text)

print('Tokens:', tokens)